#!/usr/bin/env bash

process_docker() {
   action=$1
   compose_file=$2

   tmpfile=$(mktemp)

   # Save standardized, validated config
   pushd `dirname $compose_file`
   docker-compose config > $tmpfile

   containers=($(awk '{if ($1 == "container_name:") print $2;}' $tmpfile))
   images=($(awk '{if ($1 == "image:") print $2;}' $tmpfile))

   rm $tmpfile
   popd

   for ((i=0;i<${#containers[@]};++i)); do
       container=${containers[$i]}
       image=${images[$i]}

       case $action in
           save )
               docker pull $image
               docker save $image > ${TARGET_DIR}/$container.tar
               ;;

           load )
               docker load -i ../image/$container.tar
               ;;

           delete )
               docker rmi $image
               ;;
       esac
   done
}
